# Generated by Django 5.1.6 on 2025-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="subject",
            fields=[
                ("name", models.CharField(max_length=128)),
                (
                    "code",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
